id: I64815918
default_language: de
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:32:42.551668
last_modified: 2023-01-04 11:32:42.551690
source_metadata:
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
bases:
  '5845':
    title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
    base_file: 5845.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
